[package]
name = "manage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33"
simplelog = "^0.10"
error-chain = "^0.12"
rayon = "^1.5"
indicatif = "^0.16"

base = { path = "../base" }